version: '3'
services:
  mysql-db:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs_jwt_tutorial
      MYSQL_USER: mysql_test_admin
      MYSQL_PASSWORD: password
